name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:      

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v2
        with:
          github_user_name: ibrahimif
          svg_path: ./snake.svg
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploys to gh-pages branch
          folder: .
